repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        exclude: ^(alembic/|tests/)
        additional_dependencies: [flake8-docstrings]
        args: ['--extend-ignore=D100,D101,D102,D103,D104,D105,D106,D107,D200,D202,D203,D205,D400,D401,D403']

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
    -   id: mypy
        exclude: ^(alembic/|tests/)
        additional_dependencies: [types-requests, pydantic~=2.5.2, types-redis]
        args: [--ignore-missing-imports, --disallow-untyped-defs, --disallow-incomplete-defs]
