version: "3.8"

services:
  smartpay-api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: smartpay-api
    volumes:
      - ./:/app
    ports:
      - "${API_PORT:-9000}:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      smartpay-postgres:
        condition: service_healthy
    networks:
      - smartpay-network
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-development}
      DEBUG: ${DEBUG:-True}
      SECRET_KEY: ${SECRET_KEY:-prod_change_this_to_a_secure_random_string}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      JSON_LOGS: ${JSON_LOGS:-true}
      CORS_ORIGINS_STR: ${CORS_ORIGINS_STR:-https://your-production-domain.com}
      POSTGRES_SERVER: ${POSTGRES_SERVER:-smartpay-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-smartpay}
      DATABASE_URI: ${DATABASE_URI:-postgresql+asyncpg://postgres:postgres@smartpay-postgres:5432/smartpay}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  smartpay-postgres:
    image: postgres:16
    container_name: smartpay-postgres
    env_file:
      - .env
    volumes:
      - smartpay_postgres_data_${ENV_POSTFIX:-dev}:/var/lib/postgresql/data
      - ./docker/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "${POSTGRES_PORT_EXTERNAL:-6432}:5432"
    networks:
      - smartpay-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secureprodpass}
      POSTGRES_DB: ${POSTGRES_DB:-smartpay}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  smartpay-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smartpay-pgadmin
    depends_on:
      - smartpay-postgres
    ports:
      - "${PGADMIN_PORT:-5051}:80"
    networks:
      - smartpay-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

networks:
  smartpay-network:
    driver: bridge

volumes:
  smartpay_postgres_data_dev:
  smartpay_postgres_data_prod:
  smartpay_pgadmin_data:
