services:
  # Main API service
  smartpay-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: smartpay-api
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh:ro  # SSH keys for private repositories
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      smartpay-postgres:
        condition: "service_healthy"
    networks:
      - smartpay-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # PostgreSQL database
  smartpay-postgres:
    image: postgres:15-alpine
    container_name: smartpay-postgres
    volumes:
      - smartpay_postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - smartpay-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PgAdmin for database management
  smartpay-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smartpay-pgadmin
    depends_on:
      - smartpay-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - smartpay_pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - smartpay-network

networks:
  smartpay-network:
    driver: bridge

volumes:
  smartpay_postgres_data:
  smartpay_pgadmin_data:
