"""add notif_setting column nullable with default both

Revision ID: 71e068c91fee
Revises: 8b9d57396e7d
Create Date: 2025-05-26 05:44:40.796526

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71e068c91fee"
down_revision: Union[str, None] = "8b9d57396e7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_id", table_name="notifications")
    op.drop_index("ix_notifications_user_id", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_user_notification_settings_user_id", table_name="user_notification_settings")
    op.drop_table("user_notification_settings")
    op.add_column("users", sa.Column("notif_setting", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notif_setting")
    op.create_table(
        "user_notification_settings",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("transaction_received_email", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("transaction_received_phone", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("system_messages", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="user_notification_settings_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="user_notification_settings_pkey"),
    )
    op.create_index("ix_user_notification_settings_user_id", "user_notification_settings", ["user_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("is_read", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="notifications_user_id_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="notifications_pkey"),
    )
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"], unique=False)
    op.create_index("ix_notifications_id", "notifications", ["id"], unique=False)
    # ### end Alembic commands ###
