"""add card id to transaction model

Revision ID: 8a14e5a4cc2c
Revises: 78be47d626ec
Create Date: 2025-05-23 16:08:22.686261

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8a14e5a4cc2c"
down_revision: Union[str, None] = "78be47d626ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
