"""Add meta_data fields to item model

Revision ID: bcc577d3027c
Revises: 1fc693371546
Create Date: 2025-05-17 22:04:08.265723

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcc577d3027c"
down_revision: Union[str, None] = "1fc693371546"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("meta_data", sa.JSON(), nullable=True))
    op.add_column("items", sa.Column("external_id", sa.String(length=255), nullable=True))
    op.add_column("items", sa.Column("status", sa.String(length=20), server_default="draft", nullable=False))
    op.add_column("items", sa.Column("type", sa.String(length=20), server_default="product", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "type")
    op.drop_column("items", "status")
    op.drop_column("items", "external_id")
    op.drop_column("items", "meta_data")
    # ### end Alembic commands ###
