"""Add fullname to users

Revision ID: df1858e9bca1
Revises: d203ae228b18
Create Date: 2025-05-22 00:36:22.874984

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df1858e9bca1"
down_revision: Union[str, None] = "d203ae228b18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("fullname", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "fullname")
    # ### end Alembic commands ###
