"""Create users table

Revision ID: eb1bf64bdab6
Revises: 65aed8a9a363
Create Date: 2025-05-21 19:51:12.199122

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401

from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "eb1bf64bdab6"
down_revision: Union[str, None] = "65aed8a9a363"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
