"""card id addition

Revision ID: f04a009db116
Revises: 8a14e5a4cc2c
Create Date: 2025-05-23 16:13:36.872472

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f04a009db116"
down_revision: Union[str, None] = "8a14e5a4cc2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("card_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "card_id")
    # ### end Alembic commands ###
