namespace: stage

image:
  registry: ghcr.io
  name: devnight0507/smartpay-be
  tag: latest  # Will be overwritten dynamically in CI/CD

app:
  container_name: smartpay-api-prod
  build_context: .
  dockerfile: docker/Dockerfile.dev
  host_port: 9000
  container_port: 8000
  env_file: .env.prod
  command: >
    uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  healthcheck:
    test: curl -f http://localhost:8000/api/health
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 10s
  depends_on:
    - smartpay-postgres-prod

postgres:
  container_name: smartpay-postgres-prod
  image: postgres:16
  host_port: 6432
  container_port: 5432
  env_file: .env.prod
  volume: smartpay_postgres_data_prod
  init_script: ./docker/postgres/init-db.sh
  healthcheck:
    test: pg_isready -U postgres
    interval: 5s
    timeout: 5s
    retries: 5

pgadmin:
  container_name: smartpay-pgadmin-prod
  image: dpage/pgadmin4:latest
  host_port: 5051
  container_port: 80
  admin_email: admin@example.com
  admin_password: admin
  volume: smartpay_pgadmin_data_prod
  config_server_mode: false
  depends_on:
    - smartpay-postgres-prod

network:
  name: smartpay-prod-network
  driver: bridge
