name: Build & Push Docker Image with Telegram

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  docker-build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE: ghcr.io/${{ github.repository }}
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.prod
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.VERSION }}
            ${{ env.IMAGE }}:latest

      - name: Notify Telegram – Success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="✅ *SmartPay Docker Image Built & Pushed Successfully*\n📦 Tag: \`${{ env.VERSION }}\`\n🔗 [Run Log]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" \
            -d parse_mode=Markdown

      - name: Notify Telegram – Failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="❌ *SmartPay Docker Build Failed*\n📦 Tag: \`${{ env.VERSION }}\`\n🔗 [Run Log]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" \
            -d parse_mode=Markdown
