name: Deploy 🚀 to VPS on Tag

on:
  release:
    types: [created]
  push:
    branches:
      - main
    paths:
      - 'environment/stage/values.yaml'

jobs:
  db-migrations:
      uses: ./.github/workflows/db-migration.yaml
      secrets: inherit
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract version
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.prod
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.VERSION }}
            ${{ env.IMAGE }}:latest

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Sync .env file (optional)
        if: secrets.ENV_FILE_CONTENT != ''
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" | ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cat > ${{ secrets.VPS_DEPLOY_PATH }}/.env"

      - name: Run Deployment Script on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ${{ secrets.VPS_DEPLOY_PATH }} && ./deploy.sh"

      - name: Notify Telegram – Success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="✅ *SmartPay Deployed Successfully*\n📦 Version: \`${{ env.VERSION }}\`\n🔗 [View Run]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" \
            -d parse_mode=Markdown

      - name: Notify Telegram – Failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="❌ *SmartPay Deployment Failed*\n📦 Version: \`${{ env.VERSION }}\`\n🔗 [View Run]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" \
            -d parse_mode=Markdown
